#!/bin/sh
TMPBASEDIR=$PWD;
sudo apt-get -y install qt5-default libboost-all-dev doxygen;
mkdir -p $HOME/Build/RobotSDK/Tools;
mkdir -p $HOME/Build/RobotSDK/GCC/Tools;cd $HOME/Build/RobotSDK/GCC/Tools;
qmake -makefile $TMPBASEDIR/Src/Tools/Tools.pro -r "CONFIG+=release";
make -B;
make install;
mkdir -p $HOME/Build/RobotSDK/Kernel;
mkdir -p $HOME/Build/RobotSDK/GCC/Kernel;cd $HOME/Build/RobotSDK/GCC/Kernel;
qmake -makefile $TMPBASEDIR/Src/Kernel/Kernel.pro -r -o "Makefile.Release" "CONFIG+=release";
make -f Makefile.Release -B;
make -f Makefile.Release install;
qmake -makefile $TMPBASEDIR/Src/Kernel/Kernel.pro -r -o "Makefile.Debug" "CONFIG+=debug";
make -f Makefile.Debug -B;
make -f Makefile.Debug install;
cd $TMPBASEDIR/Doc/Doxygen;
doxygen RobotSDK;
cd $TMPBASEDIR/Doc/html;
mkdir -p $HOME/SDK/RobotSDK/Doc;
cp * $HOME/SDK/RobotSDK/Doc;
rm -rf $TMPBASEDIR/Doc/html;